Feature/variabe search customizing
webitel/cc-history pull request #195
Opened 2023-09-12 14:54 UTC by VladimirBeria

2023-09-15 11:27 UTC, liza-pohranichna approved these changes

2023-09-15 11:43 UTC, dlohvinov requested changes

2023-09-15 11:43 UTC, dlohvinov commented on src/app/locale/en/en.js
> +    filterSearchHint: 'Query format: "key=value"',
ім'я ключа називається абстрактно, якийсь фільтр серч, а локаль -- конкретна, про варіейбл мод фільтр серча

2023-09-15 11:43 UTC, dlohvinov commented on src/utils/validators.js
> +  }
а чому не перевірити `value && regexp`?

2023-09-15 11:43 UTC, dlohvinov commented on src/utils/validators.js
> +export const isVariableSearch = (value) => {
я би поклав кожен валідатор в окремий файл, і назвав би (і файл і валідатор) з `Validator` у значенні -- просто бо так всюди. 
відповідно, це би називалось якось типу `variableSearchValidaror`

2023-09-15 11:43 UTC, dlohvinov commented on src/modules/main/modules/registry/api/RegistryAPIRepository.js
> +      }, {});
а який кейс закриває ця перевірка, не можу зрозуміти(
може було би правильно взагалі не відправляти невалідні варіейбли?
наприклад, фільтрувати масив варіейблів по валідатору, перед тим як його дробити на ключ-значення, чи щось таке?

2023-09-15 11:43 UTC, dlohvinov commented on src/modules/heading/modules/filters/components/filter-search.vue
> +    }
це якийсь взагалі кринж. значить, так як зроблено, не підходить
треба з у вт-серч-барі НЕ фарбувати стилями іконки, і прокидувати `invalid` у слот темплейт, і фарбувати іконки ручками самостійно

2023-09-15 11:43 UTC, dlohvinov commented on src/modules/heading/modules/filters/components/filter-search.vue
> +    },
чому не розрулити це у валідаціях, а створювати комп'ютед, який то передає, то не передає?

2023-09-15 11:43 UTC, dlohvinov commented on src/modules/heading/modules/filters/components/filter-search.vue
> +      return this.filterQuery === SearchMode.VARIABLE ? this.$t('filters.filterSearchHint') : null;
тут згоден. я би це світч-кейсом зробив, щоб "передбачити" хінти на інші моди
але може бути

2023-09-19 13:05 UTC, liza-pohranichna approved these changes

2023-09-19 14:34 UTC, dlohvinov requested changes

2023-09-19 14:34 UTC, dlohvinov commented on src/modules/heading/modules/filters/components/filter-search.vue
> +      :hint="variableSearchHint"
це неправильна назва
тут передається хінт завжди -- він не тільки варіейбл серч, а може бутии і налл
розумієш, про що я?

2023-09-19 14:34 UTC, dlohvinov commented on src/modules/heading/modules/filters/components/filter-search.vue
> +      <template v-slot:additional-actions="options">
я би зробив деструктуризацію, але то нее обов'язково, можеш зарезолвити коментар і проігнорувати
`v-slot:...={ invalid }`

2023-09-19 14:34 UTC, dlohvinov commented on src/modules/heading/modules/filters/components/filter-search.vue
> +    };
якщо написати
```
return { filterSchema: { value: this.filterQuery === ? { variableSearch } : null } } }
```
то не доведеться двічі описувати фільтр-схему)

2023-09-19 14:34 UTC, dlohvinov commented on src/modules/main/modules/registry/api/RegistryAPIRepository.js
> +          // This if else statement is needed for sending '' to backend when user writes not valid variableSearch, so we can display plug image.
`plug` у нас називається `dummy` компонентом

2023-09-20 08:51 UTC, dlohvinov approved these changes

2023-09-20 08:51 UTC, merged